steamship-core/python-client

- src/steamship/app/lambda_handler.py
- tests/steamship_tests/utils/fixtures.py
.. and fix skipped test that should have been a comment
> Add precision to plugin/app logging times

- src/steamship/plugin/outputs/raw_data_plugin_output.py
- tests/assets/plugins/importers/plugin_file_importer_by_url.py
> Return virtual bucket / filepath  in FileImporters

- src/steamship/app/lambda_handler.py
- src/steamship/app/response.py
- src/steamship/base/binary_utils.py
- src/steamship/base/client.py
- src/steamship/base/error.py
- src/steamship/data/file.py
- src/steamship/data/plugin_version.py
- tests/steamship_tests/base/test_binary_utils.py
- tests/steamship_tests/data/test_file.py
- tests/steamship_tests/plugin/unit/test_tagger.py
Sadly we can't upgrade SteamshipError to an Exception as you can't inherit from both `pydantic.BaseModel` and `Exception`.
> Remove to dict except for SteamshipError

- src/steamship/base/tasks.py
- src/steamship/data/app.py
- src/steamship/data/block.py
- src/steamship/data/plugin.py
- src/steamship/data/plugin_version.py
- src/steamship/data/tags/tag.py
- tests/steamship_tests/app/integration/test_app_instance.py
- tests/steamship_tests/data/test_plugins.py
Required for engine change: https://github.com/nludb/nludb/pull/350
> [SHIP-366] Remove upsert from non upsertable objects; Fix test

- src/steamship/data/package/package_instance.py
- src/steamship/data/plugin/plugin_instance.py
- tests/steamship_tests/app/integration/test_package_instance.py
- tests/steamship_tests/data/test_plugins.py
Depends on https://github.com/nludb/nludb/pull/386
> [SHIP-510] Add plugin / package and pluginVersion/packageVersion handles to instances

- src/steamship/invocable/invocable_request.py
- src/steamship/invocable/lambda_handler.py
Companion PR for https://github.com/nludb/nludb/pull/392.
> feat: expose owner ID for invocable in logs

- src/steamship/invocable/lambda_handler.py
- Also sends the invocableInstanceHandle to the logs
> bugfix: Ensure logging happens at the INFO level

- docs/configuration/authentication.rst
- docs/configuration/cli.rst
- docs/developing/deploying.rst
- docs/developing/project-creation.rst
- docs/index.rst
- docs/packages/using.rst
- src/steamship/cli/cli.py
This PR replaces references to the ts-cli with instructions for shippy.
Also:
- Update shippy help strings
- Minor silliness
> Shippy docs update

- src/steamship/base/tasks.py
- tests/steamship_tests/client/test_task_dependencies.py
- Adds increased timeout (3min)
- Adds callback (for status bars; I noticed that in Doug's example code)
> Improve task.wait()

- tests/steamship_tests/plugin/integration/test_e2e_generator.py
Tests the overriding of raw data fetch for ephemeral blocks
> Add test for ephemeral block output

- src/steamship/data/plugin/index_plugin_instance.py
> Wait on embedder creation when creating embedding index

- requirements.txt
- src/steamship/experimental/chatfile.py
This brings token context window counting from the package level to the ChatFile wrapper, simplifying package code for things like Telegram Buddy.
> [Experimental] move context window counting to chatfile

- src/steamship/data/block.py
- src/steamship/data/tags/tag_constants.py
- src/steamship/experimental/easy/tags.py
- src/steamship/experimental/transports/__init__.py
- src/steamship/experimental/transports/chat.py
- src/steamship/experimental/transports/steamship_widget.py
- src/steamship/experimental/transports/telegram.py
- src/steamship/experimental/transports/transport.py
Proposal:
We're about to have >5 packages which all replicate a variety of telegram hooks, and we're already seeing reports in Discord of our Telegram interactions going awry and SMS-bombing folks.
I think there's a lot of safety / value in pulling today's sketch of the Telegram code into a managed wrapper and then relying on that wrapper.
It will change, but we just manage that by updating it here and then bumping the Steamship version, so I think this is a strict safety-adder. 
Folks generally OK w/ this?
> Proposal - Experimental Telegram Helpers

- src/steamship/agents/examples/my_assistant.py
- src/steamship/agents/react/output_parser.py
- src/steamship/experimental/package_starters/telegram_agent.py
- tests/steamship_tests/agents/test_react_parse_output.py
This allows Telegram (and other transports) to appropriately send them
> LLM Ouptut Parsing back into Blocks

- src/steamship/agents/react/output_parser.py
- src/steamship/agents/service/agent_service.py
- src/steamship/agents/tools/search/search.py
- tests/steamship_tests/app/unit/test_routes_on_superclasses.py
Added some more for context on what was being sent to individual tools.
> add: inputs to logging for tool

- src/steamship/agents/tools/base_tools.py
> Hotfix: Fix requests in ScrapeAndBlockifyTool

- src/steamship/invocable/lambda_handler.py
- tests/assets/packages/safe_loaded_hello_world.py
This allows us to push extra structured contextual information through to the logs
> Make 'extra' logging content flow through as structured data to Elastic

- src/steamship/agents/tools/audio_transcription/assembly_speech_to_text_tool.py
- src/steamship/agents/tools/audio_transcription/fetch_audio_urls_from_rss_tool.py
- src/steamship/agents/tools/audio_transcription/whisper_speech_to_text_tool.py
- src/steamship/agents/tools/classification/sentiment_analysis_tool.py
- src/steamship/agents/tools/classification/zero_shot_classifier_tool.py
- src/steamship/agents/tools/conversation_starters/knock_knock_tool.py
- src/steamship/agents/tools/image_generation/dalle.py
- src/steamship/agents/tools/image_generation/google_image_search.py
- src/steamship/agents/tools/image_generation/stable_diffusion.py
- src/steamship/agents/tools/question_answering/prompt_database_question_answerer.py
- src/steamship/agents/tools/search/search.py
- src/steamship/agents/tools/speech_generation/generate_speech.py
- src/steamship/agents/tools/text_generation/image_prompt_generator_tool.py
- src/steamship/agents/tools/text_generation/personality_tool.py
- src/steamship/agents/tools/text_generation/text_translation_tool.py
- src/steamship/agents/tools/video_generation/did_video_generator_tool.py
Fixes Issue #415 -- thank you @MikPoik!
> Fix __main__ function in several tools -- the LLM was missing

- src/steamship/cli/cli.py
- src/steamship/cli/create_instance.py
- src/steamship/cli/local_server/server.py
This PR fixes ship serve --ngrok by 
* Switching to  HTTPS (required for Telegram) 
* Adding the same config-loading flow as ship use
> Fix ship serve ngrok

- docs/packages/developing/project-structure.rst
- tests/assets/packages/example_project_structure.py
- tests/steamship_tests/app/integration/test_example_project_structure.py
> Update docs for Example Package Structure

- docs/packages/cookbook/collecting-and-querying-sentiment.rst
> Update Sentiment Docs

- src/steamship/agents/examples/my_functions_based_assistant.py
- src/steamship/agents/functional/__init__.py
- src/steamship/agents/functional/functions_based.py
- src/steamship/agents/functional/output_parser.py
- src/steamship/agents/llms/openai.py
- src/steamship/agents/react/output_parser.py
- src/steamship/agents/schema/__init__.py
- src/steamship/agents/schema/action.py
- src/steamship/agents/schema/agent.py
- src/steamship/agents/schema/chathistory.py
- src/steamship/agents/schema/llm.py
- src/steamship/agents/service/agent_service.py
- src/steamship/agents/tools/image_generation/dalle.py
- src/steamship/data/block.py
- src/steamship/data/tags/tag_constants.py
- tests/steamship_tests/agents/test_functions_based_agent.py
This is meant to provide a basic implementation of an agent that works with tools using OpenAI's functions extension as the mechanism for tools selection. This is an initial implementation that will likely need refinement as use cases are explored.
> feat(agents): add functions-based agent to SDK

- tests/assets/packages/requirement_isolation_package.py
- tests/steamship_tests/app/integration/test_requirements_installation_isolation.py
- tests/steamship_tests/utils/deployables.py
Tests the requirements isolation of concurrent deployments.
> [SHIP-535] test needed ensure deployments cannot leak

- src/steamship/agents/functional/output_parser.py
- src/steamship/agents/llms/openai.py
- src/steamship/agents/schema/llm.py
- src/steamship/utils/repl.py
- tests/steamship_tests/agents/test_openai.py
This was a user request in Discord: https://discord.com/channels/927675537390968882/1128101636053680148
> feat(agents): allow max_token specification in LLMs

- .github/workflows/test-main.yml
Disclaimer: I have no idea if this will work the way I think it should.
> feat(merge queues): attempt a merge queue for the main branch

- src/steamship/agents/examples/fact_learner.py
- src/steamship/agents/service/agent_service.py
- src/steamship/agents/tools/question_answering/vector_search_learner_tool.py
- src/steamship/agents/tools/question_answering/vector_search_qa_tool.py
- tests/steamship_tests/agents/tools/test_fact_learner_tools.py
OpenAI functions for QASearch weren't being reliably called. This creates a better tool description (the human description is used in the functions-based agent). A test is added to validate continued ability to work.
> fix(tools): add better description for vectorsearch tool and a test

- src/steamship/invocable/dev_logging_handler.py
> fix(logs): fix windows-related issues to logs file

- src/steamship/agents/react/output_parser.py
- src/steamship/agents/react/react.py
`Action::tool` is now a `str` and not an obj of type `Tool`.
> fix(react): update code to match caching refactor of Action

- src/steamship/agents/service/agent_service.py
- tests/steamship_tests/agents/test_agent_limits.py
Per request: https://discord.com/channels/927675537390968882/1156666953440698498
> Limit specific tools by name

- src/steamship/agents/schema/functions.py
- src/steamship/data/manifest.py
- src/steamship/invocable/config.py
- tests/steamship_tests/app/unit/test_config_template_extraction.py
- tests/steamship_tests/utils/test_enums.py
Release  coordination issue -- engine-side support still to come
> Re-comment out optional support

- src/steamship/agents/llms/openai.py
- src/steamship/data/file.py
ChatOpenAI will soon be consolidated, but this fixes a resource leak within it.
Also adds more helpful type hinting on File.
> Fix temp file resource leak

- src/steamship/agents/schema/chathistory.py
- src/steamship/cli/cli.py
(Noticed this causing failures with some of the game code.)
> bugfix: ChatHistory -- skip embedding whitespace-only text

- src/steamship/cli/deploy.py
to fix issue with deployment from Replit (see https://discord.com/channels/927675537390968882/1162470366619377766)
> Add strict_timestamps=False
