steamship-core/python-client

src/steamship/utils/huggingface_helper.py
- Set default timeout to 30 sec instead of 10
- Allow passing timeout per usage
- Don't tell HF to wait on the model per call
=> Change timeout / wait settings on HF Helper

DEVELOPING.md, src/steamship/plugin/inputs/raw_data_plugin_input.py, src/steamship/utils/signed_urls.py, tests/assets/plugins/taggers/plugin_trainable_tagger.py, tests/assets/plugins/taggers/plugin_trainable_tagger_config.py, tests/tests/plugin/unit/test_service.py, tests/tests/plugin/unit/test_trainable_tagger.py, tests/tests/plugin/unit/test_trainable_tagger_config.py
Some files are too large to comfortably send as Base64
within JSON. The Steamship Engine sometimes chooses to send an empty `data` field paired with a non-empty
`url` field. When this happens, the constructor proactively, synchronously fetches the contents of that `url`
and assigns it to the `data` field, throwing a SteamshipError if the fetch fails. Again, this is done
automatically so the Plugin Author can mostly ignore this fact.
=> Support url-conveyed data in RawDataPluginInput

src/steamship/app/lambda_handler.py, src/steamship/app/request.py, src/steamship/app/response.py, src/steamship/base/error.py, tests/assets/apps/demo_app.py, tests/assets/plugins/importers/plugin_file_importer_python_error.py, tests/assets/plugins/importers/plugin_file_importer_steamship_error.py, tests/tests/app/integration/test_app_error_visibility.py, tests/utils/fixtures.py
This is the Python-side work of building end-to-end Exception visibility into our test suite.
It tests that
* Unexpected python Exceptions
* thrown SteamshipErrors
* missing method calls
Are all reported to the user as an appropriately formatted SteamshipResponse object.
The built-in testing app now contains a few functions  which are intended to generate errors with known messages. The test invokes those functions and assertions are placed on the HTTP response object.
This PR includes a PyTest fixture which makes it very easy to test a Steamship App from the perspective of the HTTP caller without actually doing a full deploy & round trip to the engine.
It is useful to have some tests which actually do this full round trip, but aside from testing that the round trip works, we probably …
=> Unit test expected error responses of apps/plugins

src/steamship/app/app.py, src/steamship/app/lambda_handler.py, src/steamship/app/request.py, src/steamship/base/tasks.py, src/steamship/data/file.py, src/steamship/data/user.py, src/steamship/plugin/config.py, src/steamship/plugin/inputs/block_and_tag_plugin_input.py, src/steamship/plugin/inputs/raw_data_plugin_input.py, src/steamship/plugin/outputs/block_and_tag_plugin_output.py, src/steamship/plugin/outputs/embedded_items_plugin_output.py, tests/assets/apps/demo_app.py, tests/tests/app/integration/test_app_error_visibility.py, tests/tests/app/unit/test_response.py, tests/tests/base/test_binary_utils.py, tests/tests/base/test_task.py, tests/tests/plugin/unit/test_service.py, tests/utils/fixtures.py, tests/utils/test_enums.py
Title says it all. 
Reasons to do this: 
- All comms with server happen in camelCase. 
- Picking 1 option over 2 leaves less room for surprises 
- CamelModel works just like BaseModel without the `by_alias=True` option
Going to develop a pre-commit hook that checks if we are using BaseModel in the future.
=> Swap out BaseModel in favour of CamelModel

src/steamship/app/lambda_handler.py
A missing `s` was causing every call to `log.*` to crash the whole lambda!
=> Fix bug in logging formatter

src/steamship/app/app.py, src/steamship/plugin/outputs/raw_data_plugin_output.py, src/steamship/plugin/service.py, tests/assets/apps/demo_app.py, tests/assets/plugins/importers/plugin_file_importer_by_url.py, tests/steamship_tests/plugin/integration/test_e2e_file_importer_by_url.py
This PR allows large file imports beyond the size limit of lambda return values.  The FileImporter plugin must create a steamship signed URL, and pass that as a return value in RawDataPluginOutput.
Along the way, I had to make a change so that Plugins/Apps would get a handle to a Steamship object instead of a Client object.
Depends on engine PR #304.
=> Python sdk changes for large FileImport

src/steamship/base/response.py, tests/steamship_tests/server/test_task_timeout.py
Making wait() throw an exception if it times out without the task completing.  Previously it would just happily return, which led to odd behavior when trying to use .data.
=> SteamshipResponse.wait() throws on timeout

src/steamship/app/lambda_handler.py, tests/steamship_tests/base/test_steamship_error_serializable.py
Currently in elastic logs for python client we sometimes see CRITICAL - can't output to log.  This is because we sometimes call logging with an exception directly, ex:
```
error = SteamshipError("Something is amiss!")
logging.error(error)
```
The 'cant output to log' is because the SteamshipError is not msgpack serializable.  This PR makes SteamshipError msgpack serializable with its to_dict method, and makes any other exception serializable with its args.
=> Add serializer for exceptions for remote logging

docs/index.rst
This might help people quickly jump back and forth between the docs and what's immediately available to play with.
If we'd prefer to link to the `Packages` page of the same doc site instead, that'd be OK too.
=> add: link to Steamship plugin registry doc page

requirements.txt
aiohttp==3.8.1 didn't support python 3.11. 3.8.2 and 3.8.3 do.
=> Support Python 3.11

src/steamship/data/file.py, tests/assets/plugins/importers/plugin_file_importer.py, tests/assets/plugins/importers/plugin_file_importer_by_url.py, tests/assets/plugins/importers/plugin_file_importer_python_error.py, tests/assets/plugins/taggers/plugin_embedder.py, tests/assets/plugins/taggers/plugin_logging_tagger.py, tests/assets/plugins/taggers/plugin_parser.py, tests/assets/plugins/taggers/plugin_third_party_trainable_tagger.py, tests/steamship_tests/data/test_file.py, tests/steamship_tests/plugin/unit/test_service.py, tests/steamship_tests/utils/client.py
Note - most of the changed lines in this PR are just making black and pycln happy again - somehow we got into a state where the files unmodified by this PR did not meet their standards.  I wanted these fixed so that we could see the green check again.
=> [SHIP-461] Refresh updates self object (no need to reassign to variable)

tests/steamship_tests/utils/deployables.py
This is in service of remote packaging work
=> Write empty requirements in test deployments

src/steamship/data/tags/tag.py
I'm going to try splitting up the embedding refactor into several smaller commits.
All of our conversations around design involved the `Tag` field gaining a `text` field so that it could be stored/retreived/worked-with as an atomic object separate from the file from which it came.
This PR adds that field.
=> Add a text field to `Tag`

src/steamship/base/package_spec.py, src/steamship/invocable/invocable.py, tests/assets/demo_package_spec.json, tests/assets/packages/demo_package.py, tests/steamship_tests/app/unit/test_demo_app_spec.py
There's value in exploring the possibility of "public" package endpoints:
* Certain operations, like web hooks, are not configurable with an `Authentication` header. The Telegram bot api is an example of this.
* Hosting a simple web UI from within a package 
* Hosting an endpoint that a web form or other unauth'ed user could post to
One way to support this would be via an annotation, such as:
```
@post("/add-data", public=True)
def add_data(self..)
```
This PR transforms all primitive-valued kwargs after the `path` in the @get and @post comments into a `config` object which is returned in the __dir__ object.
This permits us to experiment with support for things like public endpoints without having to fiddle with custom client versions; we just put it in the kwargs and have the engine …
=> Add a `config` object on method registration, to be returned in __dir__

src/steamship/base/client.py, src/steamship/data/file.py, src/steamship/data/package/package_version.py, src/steamship/data/plugin/plugin_version.py, tests/steamship_tests/data/test_file.py
There are two ways to create a file:
* Provide Block JSON (blocks and tags)
* Provide content
There's a third way which should be supported:
* Provide content along with file-tags
But when `File.create` was called with both `content` and `tags`, the client would incorrectly set the upload type to BLOCK_JSON, which would result in an empty file (but one that contained tags).
This PR changes the behavior of File.create to make the upload type decision based only on the presence/absence of `blocks` or `content` --- not the `tags` property. 
This should allow for files to be created with `File.create(content=..., tags=...)`
Fixing this bug uncovers a new bug lurking in our multi-part POST handling. It's probably been there all along and we just never noticed.
When running the new test:
``` …
```
=> Fix two bugs: File.create when both `content` and `tags` are present, and multipart Mime-posting of nested objects

src/steamship/utils/kv_store.py, tests/steamship_tests/utils/test_kv_store.py
Was goofing off in the package layer and found utility in this:
- The more people build real things in packages, the more they'll need the ability to store app data
- This is a small change that adds a way to treat the KV store as a list of KV Pairs that you can set; e.g. dynamic user settings for the package or some external app that's using Steamship as a data store.
=> Add a `list` method to the KVStore class.

src/steamship/invocable/lambda_handler.py, tests/steamship_tests/app/unit/test_demo_app_spec.py
Required to allow use of `/__dir__`-based healthchecks against "fake" instances that are not fully-configured. This will allow additional confidence that a package version can be used (and marked as default, etc.)
=> feat: add support for directory listing without creating an instance

src/steamship/base/client.py, src/steamship/base/tasks.py, src/steamship/invocable/invocable.py, src/steamship/invocable/lambda_handler.py, src/steamship/invocable/package_service.py, src/steamship/invocable/plugin_service.py, tests/assets/demo_package_spec.json, tests/assets/packages/demo_package.py, tests/assets/plugins/blockifiers/tsv_blockifier.py, tests/assets/plugins/taggers/plugin_trainable_tagger.py, tests/assets/plugins/taggers/plugin_trainable_tagger_config.py, tests/steamship_tests/app/integration/test_package_instance.py, tests/steamship_tests/app/unit/test_demo_app_spec.py, tests/steamship_tests/utils/fixtures.py
**Tests green against `engine@main` but will fail on prod/staging since they're not up to date**
This adds a new method to the `Invocable` class called `invoke_later` which schedules an invocation against that Invocable's own method call. This enables sequences of long-running operations to be chained together by a package.
In order to implement this, a new variable needed to be passed into the Invocable -- the InvocationContext. That is now a piece of the base-class init method and has to be plumbed down by any plugins/packages that choose to implement their own custom init.
=> Adds an `invoke_later` method to invocables

.github/workflows/test-main.yml, requirements.dev.txt, tests/steamship_tests/app/integration/test_package_instance.py, tests/steamship_tests/base/test_configuration.py
This PR attempts to setup tests against Staging and Production in a way that allows Staging tests to provide ultimate validation while Production provide advisory information. This _should_ allow for evolution of the client away from Production, keeping in sync with Staging, during development.
This also sets up JUnit reporting tasks for tests to all better test failure inspection directly from the GH status page.
=> fix: run tests against staging as well as prod for main branch

src/steamship/data/plugin/plugin_instance.py, tests/steamship_tests/plugin/integration/test_e2e_trainable_tagger.py
Add more params to train method, allowing one-line invocation, and avoiding the possibility of passing a different plugin instance.  Leave the old way for back-compat.
=> [SHIP-511] Add easier version of PluginInstance.train

docs/api/steamship.invocable.rst, docs/packages/cookbook/index.rst, docs/packages/cookbook/return-audio.rst, docs/packages/cookbook/return-image.rst, docs/packages/cookbook/return-json.rst, docs/packages/cookbook/return-text.rst, src/steamship/base/client.py, src/steamship/client/steamship.py, src/steamship/data/plugin/index_plugin_instance.py, src/steamship/data/plugin/prompt_generation_plugin_instance.py, src/steamship/data/plugin/prompt_plugin_instance.py, src/steamship/data/tags/tag.py, tests/assets/plugins/taggers/plugin_configurable_tagger.py, tests/assets/plugins/taggers/plugin_prompt_generator.py, tests/steamship_tests/plugin/integration/test_e2e_configurable_tagger.py, tests/steamship_tests/plugin/integration/test_e2e_prompt_plugin.py, tests/steamship_tests/plugin/integration/test_use_skill.py, tests/steamship_tests/utils/client.py
This PR introduces our second PluginInstance subclass -- `PromptGenerationPluginInstance`.
It changes no semantics of how plugins, tagging, or existing LLM plugins work; it only acts as a convenience wrapper around PluginInstances that happen to be associated with an LLM tagger.
* It adds a `generate(prompt, prompt_variables)` method which synchronously returns a string.
* It adds an output sanitization method.
Using this new subclass, one can invoke an LLM with two lines of code and two lines of data:
```
PROMPT = "Greet {name} as if he were a {relation}."
VARIABLES = { "name": "Ted", "relation": "friend" }
llm = Steamship.use('prompt-generation-default', config={ "temperature": 0.9 })
greeting = llm.generate(PROMPT, VARIABLES)
```
* The implementation of `generate` is copy-pasted …
=> Playing around with simplified prompt interface

pyproject.toml, requirements.txt, src/steamship/base/client.py, src/steamship/base/configuration.py, src/steamship/cli/cli.py, src/steamship/cli/deploy.py, src/steamship/cli/login.py, src/steamship/cli/manifest_init_wizard.py, src/steamship/cli/ship_spinner.py, src/steamship/data/package/package.py, src/steamship/invocable/config.py, src/steamship/invocable/invocable.py, src/steamship/invocable/lambda_handler.py, src/steamship/invocable/manifest.py, tests/assets/packages/configurable_hello_world.py, tests/assets/plugins/blockifiers/blockifier.py, tests/assets/plugins/blockifiers/csv_blockifier.py, tests/assets/plugins/taggers/plugin_configurable_tagger.py, tests/assets/plugins/taggers/plugin_trainable_tagger.py, tests/assets/plugins/taggers/plugin_trainable_tagger_config.py, tests/steamship_tests/app/unit/test_config_template_extraction.py, tests/steamship_tests/plugin/unit/test_service.py
This PR builds in a minimal first CLI directly into the Python SDK package.
It currently supports only two commands:
`ship login`
`ship deploy`
and the latter only supports packages.
New features vs. Typescript CLI:
- If no auth is available, will try to login on instantiation of `Steamship()`.  If no browser available, throws exception.
- If `steamship.json` doesn't exist during deploy, walk the user through creation
- deploy command will update config template based on the Config python object in the package (outputs the new template if changed)
- If a package handle already exists and is owned by someone else, the deploy will prompt the user for a new one 
Plugin support will be straightforward to add (mostly more manifest fields), but left it out so we could get rolling with this.
=> Python Mini CLI

src/steamship/cli/deploy.py
Disclaimer: I have no idea what I'm doing here. The code could use a bunch of refactoring, if it is even the "right" solution. This is merely an attempt at sketching out a possible approach. 
Problem statement:  Running `ship deploy` with more than just `api.py` in your package breaks because of modules not being found.
This PR attempts to address that by recursing through the directories with python files and trying to load (and exec?) them.
I have only validated this with parallel files and **one** package at a subdirectory. I have not validated this with more complex deployments, etc. As soon as I got _something_ working, I pushed this PR to allow for others to play and optimize while I sleep.
=> attempt to fix import issue

src/steamship/client/steamship.py, src/steamship/utils/metadata.py, tests/steamship_tests/app/integration/test_use_package.py, tests/steamship_tests/plugin/integration/test_use_plugin.py
Steamship configs are immutable; the following two lines will error because they attempt to load the same package instance (`instanceHandle`) with differing configurations:
```
Steamship.use('packageHandle', 'instanceHandle', config={"name"="Larry"}) # Sometimes works; if not done before with different config
Steamship.use('packageHandle', 'instanceHandle', config={"name"="Curly"}) # Always fails, since we know config differs
```
When the instanceHandle is not provided, a default is provided, equal to the packageHandle/pluginHandle:
```
Steamship.use('packageHandle', config={"name"="Larry"}) # Sometimes works; if not done before with different config
Steamship.use('packageHandle', config={"name"="Curly"}) # Always fails, since we know config differs
```
This is good in that it hard-errors …
=> Add configuration  hash to auto-named handles

src/steamship/base/client.py, src/steamship/cli/cli.py
This adds a command to the `ship` CLI to support logs retrieval.
Users can use it in conjunction with `jq` to retrieve and parse logs in their workspaces (filtering by package/instance/version/path).
Example usage:
```bash
ship logs --workspace my-prod-workspace  --path '/generate'  | jq '.entries[].message'
```
This should allow developers to quickly access pertinent logs for their packages without having to visit the web UI.
=> feat: add logs retrieval to ship cli

src/steamship/data/embeddings.py, src/steamship/data/plugin/index_plugin_instance.py
This isn't really a fix, but possibly a reliability band-aid for vector search
=> Explicitly wait on snapshot creation in index_plugin_instance

src/steamship/base/client.py, src/steamship/base/configuration.py, tests/assets/packages/demo_package.py, tests/steamship_tests/app/integration/test_package_instance.py, tests/steamship_tests/base/test_serialization.py
Better safe than sorry. Preventing log leakage with API Keys, etc., seems like the right default stance.
=> default to protecting api key in serializations

src/steamship/data/embeddings.py, src/steamship/data/plugin/index_plugin_instance.py, tests/steamship_tests/client/operations/test_embedding_index.py
This is an additional mitigation towards issues with failed embedding index insertions.  If you attempt to embed a string longer than 5000 characters, it will be rejected within the SDK unless you pass the override flag.
=> Block large embeddings before insertion (with available override)

tests/steamship_tests/base/test_configuration.py, tests/steamship_tests/utils/deployables.py
- It's no longer necessary to wait on deploying things, as the deploy chain includes health check and thus waits engine-side
- Skip the empty API key test when running in an env with a browser (locally) so that it doesn't try to log you in
=> Two Minor test improvements

src/steamship/base/client.py, src/steamship/data/package/package_instance.py, tests/steamship_tests/app/integration/test_package_instance.py
Helpful for applications that might need to bail out quickly if the service doesn't respond (ex: Clockbot) :)
=> Add optional HTTP timeouts to package invocations

src/steamship/base/client.py, tests/steamship_tests/client/operations/test_embedding_index.py
This PR makes it so that the index plugin instance won't gloss over the failure to insert a record.
The fix is broader, though - any non OK statuses in client.call will now throw an error instead of returning String.
=> Fail on bad results from server

src/steamship/base/client.py, tests/steamship_tests/data/test_file.py
Steamship should be a good 🚢 . A good ship should not lie to users. It would be a lie to tell a user that a File was created when the object returned is not a File. Hence, Steamship must enforce expectations.
Without this PR, it is possible, though rare, for the following to happen:
```
f = File.create(client=client, blocks=[Block(text="something filtered by WAF")])
print(f.handle)
```
```
steamship.base.error.SteamshipError: ... | 'str' object has no attribute 'handle'
```
=> fix: ensure expectation is met in lookups/creates

src/steamship/data/plugin/index_plugin_instance.py
Now that the engine auto-snapshotting has been validated on staging, this PR should go in to allow the SDK to take advantage
=> Don't snapshot in index plugin instance; let the engine do it

src/steamship/data/tags/tag_constants.py
Add tag constants for Roles, which will allow easy labelling of content for use in OpenAI chat completion interface.
=> Add role constants

src/steamship/invocable/invocable_request.py
Companion PR to: https://github.com/nludb/nludb/pull/535
The idea is to allow packages to dynamically provide manifests that use their domain-specific invocation URL.
Concerns:
- Exposes user workspace handles to owners
- Exposes owner handles to users
=> feat: add owner and workspace handles to invocation context

src/steamship/base/request.py, src/steamship/base/response.py, src/steamship/base/tasks.py, src/steamship/data/embeddings.py, src/steamship/data/file.py, src/steamship/data/plugin/plugin.py, src/steamship/data/workspace.py, tests/steamship_tests/client/operations/test_embedding_index.py, tests/steamship_tests/data/test_file.py, tests/steamship_tests/data/test_plugins.py, tests/steamship_tests/data/test_task_comments.py, tests/steamship_tests/data/test_workspace.py
Companion PR to https://github.com/nludb/nludb/pull/483.
This adds support for paging in the python SDK for objects that support a `list` call currently.
=> feat: add paging to list operations in client SDK

src/steamship/invocable/invocable.py, tests/steamship_tests/app/unit/test_routes_on_superclasses.py
This tests a fix (in the same PR) to a behavior in which each new Subclass of Invocable would register its route
table afresh, overwriting whatever routes were registered by an ancestor.
=> Allow parent Invocables to register routes exposed on the children Invocables

src/steamship/cli/cli.py
This provides users (replit, hackathon, cli, discord) with a quick way to see if their environment is set up correctly.
=> feat: Add `ship info` command for helping users diagnose whether their environment is set up

src/steamship/invocable/invocable.py
Without this PR, attempting to run the collab script linked from our website (https://colab.research.google.com/drive/1r-LkB1vgbc6LHpK0MiDWLl0_jU2nSw50#scrollTo=L_5kDYuh5YWg) results in the following:
```
---------------------------------------------------------------------------
FileNotFoundError                         Traceback (most recent call last)
[/usr/local/lib/python3.10/dist-packages/steamship/invocable/invocable.py](https://localhost:8080/#) in __init__(self, client, config, context)
112         try:
--> 113             secret_kwargs = toml.load(".steamship/secrets.toml")
114         except FileNotFoundError:  # Support local secret loading
4 frames
FileNotFoundError: [Errno 2] No such file or directory: '.steamship/secrets.toml'
During handling of the above exception, another …
```
=> fix: collab support

src/steamship/plugin/generator.py
Currently, it's not possible to write an async generator plugin, because the shim code in generator.py attempts to rewrite data.  In the async case, where data is not yet filled, this will throw an error.
This PR adds a condition so that the blocks are only rewritten if data is present.
=> On generator return, only rewrite blocks if the result has data

src/steamship/invocable/lambda_handler.py
In merging the handler and local_handler code in #343 , I accidentally introduced an issue where instance init was being called once per invocation even when deployed to lambda.  This change should fix.
=> Bugfix: Double instance_init

src/steamship/experimental/package_starters/telegram_bot.py, src/steamship/experimental/transports/steamship_widget.py, src/steamship/experimental/transports/telegram.py, src/steamship/experimental/transports/transport.py
If the telegram bot joins a group, or receives an image, it gets a message with no text value.  Rather than this throwing an error in parse_inbound, we return None, so that the bot can decide not to reply without try/except.
=> Make parse inbound returns optional

src/steamship/experimental/package_starters/telegram_bot.py, src/steamship/experimental/package_starters/web_bot.py, src/steamship/experimental/transports/chat.py
This PR makes the response format of the webbot compatible with what is currently supported by the front end.  
I also added the field `who` to ChatMessage so we wouldn't need a hacky way to include that field in our response (by default we ignore fields that aren't defined in the spec). For context, here's how the hackathon project added the who field: 
🚨 This PR temporarily removes support for source attribution. This will be added back in a follow-up PR to decide if and how sources fit into ChatMessage responses.
=> Fix web-bot

docs/agents/index.rst, docs/api/steamship.agents.examples.rst, docs/api/steamship.agents.llms.rst, docs/api/steamship.agents.memory.rst, docs/api/steamship.agents.react.rst, docs/api/steamship.agents.rst, docs/api/steamship.agents.schema.rst, docs/api/steamship.agents.service.rst, docs/api/steamship.agents.tools.audio_transcription.rst, docs/api/steamship.agents.tools.classification.rst, docs/api/steamship.agents.tools.conversation_starters.rst, docs/api/steamship.agents.tools.image_generation.rst, docs/api/steamship.agents.tools.question_answering.rst, docs/api/steamship.agents.tools.rst, docs/api/steamship.agents.tools.search.rst, docs/api/steamship.agents.tools.speech_generation.rst, docs/api/steamship.agents.tools.text_generation.rst, docs/api/steamship.base.rst, docs/api/steamship.cli.local_server.rst, docs/api/steamship.cli.rst, docs/api/steamship.experimental.easy.rst, docs/api/steamship.experimental.package_starters.rst, docs/api/steamship.experimental.rst, docs/api/steamship.experimental.transports.rst, docs/api/steamship.invocable.rst, docs/api/steamship.plugin.outputs.rst, docs/api/steamship.rst, docs/api/steamship.utils.rst, docs/index.rst
This is very basic, but just wanted to have some links from the front page that could navigate you to some info about Agents and to the Guidebook.
(you can ignore everything in the PR except docs/agents/index.rst and docs/index.rst)
=> Update docs for agents

src/steamship/base/package_spec.py, src/steamship/invocable/invocable.py, tests/assets/demo_package_spec.json, tests/steamship_tests/app/integration/test_instance_init.py, tests/steamship_tests/app/integration/test_package_error_visibility.py, tests/steamship_tests/app/unit/test_demo_app_spec.py, tests/steamship_tests/app/unit/test_routes_on_superclasses.py, tests/steamship_tests/client/test_task_dependencies.py
This PR contains a slight refactoring of `Invocable`'s route registration code to make it easier for an `Invocable` instance to (1) register routes on itself, and (2) register routes against arbitrary function pointers.
At present, route registration is done at the class-level, inside `__init_subclass__`, by associating HTTP routes with the **names** of functions to be called (rather than a pointers to that function).
This creates a number of frictions:
- It's very challenging for an Invocable instance (rather than classdef) to register a route
- It's very challenging for a helper library to contribute routes that should be mixed-in to an Invocable 
For example, the following things are near-impossible with our class-only registration system:
- Dynamically adding a new transport to (e.g. …
=> feat: Make easier for Invocable instance to register a route

docs/data/blocks.rst, docs/data/files.rst, docs/plugins/using/generators/index.rst, src/steamship/data/block.py, src/steamship/data/file.py, tests/steamship_tests/data/test_block.py, tests/steamship_tests/data/test_file.py
The previous public_data PR did not include a method for altering the `public_data` status of a `Block` or `File`.  
This PR introduces `set_public_data` on both.
=> Allow setting of public_data from block and file

src/steamship/cli/create_instance.py
This PR changes the behavior of ship use as follows: 
1. For each non-default variable: 
* Use matching env variable to load value 
* Ask user for input when matching env variable is not found
2. Store new user-defined input in a config file
=> Upgrade `ship use`: ask for input on non-default variables

src/steamship/agents/llms/openai.py, src/steamship/agents/tools/text_generation/summarize_text_with_prompt_tool.py
This provides a way to control the "creativity" of the OpenAI LLM in Agents. Combined with the AgentContext LLM storage, this allows builders to use a "less creative" LLM for Action selection and a "more creative" LLM for user interactions.
=> feat(agents): add temperature control to OpenAI LLM

src/steamship/agents/schema/context.py, src/steamship/agents/utils.py
This explains the previously unexplainable #409 .
```
>>> class A:
...    a_list=[]
...    def __init__(self):
...       self.a_list.append("a")
...
>>> a = A()
>>> a.a_list
['a']
>>> b = A()
>>> b.a_list
['a', 'a']
The gist being that a_list is a static class var, at least until you would overwrite it with an instance-level version:
>>> a.a_list = ['b']
>>> a.a_list
['b']
>>> b.a_list
['a', 'a']
```
=> Fix python insanity

src/steamship/cli/cli.py
Updated output.
```
Usage: ship [OPTIONS] COMMAND [ARGS]
Options:
--help  Show this message and exit.
Commands:
deploy  Deploy the package or plugin in this directory
info    Displays information about the current Steamship user.
it      Deploy the package or plugin in this directory
login   Log in to Steamship, creating ~/.steamship.json
logs    Retrieve logs within a workspace.
serve   Serve the local invocable
ships   Ship some ships
use     Create an instance of your package/plugin for use.
```
=> fix(cli): ensure 'logs'  command has a message when '--help' is invoked.

src/steamship/agents/tools/question_answering/vector_search_qa_tool.py, src/steamship/agents/tools/text_generation/json_object_generator.py, src/steamship/agents/tools/text_generation/text_rewrite_tool.py, src/steamship/agents/utils.py
This provides our initial Tools with a "safer" way of getting an LLM as needed to perform their tasks.
Stylistically, there is a larger conversation to be had about the "right" way of passing LLMs to Tools, but this at least prevents  problematic usage with the existing pattern.
Fixes #415
=> fix(llm lookup): allow Tools to specify fallback LLMs in lookups

src/steamship/cli/cli.py, src/steamship/cli/local_server/handler.py, tests/steamship_tests/app/integration/test_e2e_mixins_importer_blockifier.py
This adds a user interface to development-mode agents.
```
ship serve --ui
```
Will generate a URL that will bring up a web browser that connects to the local agent.
Requires a corresponding 
https://github.com/steamship-core/python-client/assets/63262/64c9fb1b-ba4f-421f-84bf-9b7307e7e3f2
=> cli: Add user interface to development-mode agents

src/steamship/base/package_spec.py, src/steamship/invocable/invocable.py, src/steamship/invocable/package_service.py, tests/assets/demo_package_spec.json, tests/steamship_tests/app/unit/test_mixins.py
This fixes the reported issue where superclasses can't register mixins for you.
=> Keep track of already registered mixins

src/steamship/cli/cli.py, src/steamship/cli/local_server/handler.py, src/steamship/cli/local_server/server.py
The `invocable_url` on the context represents the externally-visible URL of the instance.
When running on localhost, this should include the port that the local server is running on.
But when running with NGROK involved, the local port is within the ngrok pipe, and the ngrok url should be used without modification.
=> When using ngrok, don't append the local port to `invocable_url`

tests/steamship_tests/app/integration/test_e2e_mixins_indexer_pipeline.py
The test below was frequently failing to complete in the required time period in the CICD pipeline.
This update uses a much shorter example PDF file, reducing the time taken to complete.
=> Update Long Running / Flaky test

src/steamship/invocable/mixins/file_importer_mixin.py, tests/steamship_tests/app/integration/test_e2e_mixins_indexer_pipeline.py
The last PDF document I changed this test to stopped working.
I've altered the PDF again; if this one stops working I will upload one to somewhere under our control.
The previous test not working also highlighted a wrong-import problem with the logs in the mixin, which is fixed here.
=> Fix index pipeline mixin test again

docs/api/steamship.agents.mixins.rst, docs/api/steamship.agents.mixins.transports.rst, docs/api/steamship.agents.tools.video_generation.rst, docs/api/steamship.invocable.mixins.rst, docs/api/steamship.rst, docs/conf.py, docs/packages/cookbook/adding-configuration.rst, docs/packages/cookbook/article-tagging.rst, tests/assets/packages/adding_configuration.py, tests/assets/packages/article_tagging.py, tests/steamship_tests/app/integration/test_adding_configuration.py, tests/steamship_tests/app/integration/test_article_tagging.py
This updates the exposed docs as follows:
- Fixes the configuration example for two articles (per reported issue)
- Hides the article tagging cookbook recipe (pending restoration of function from plugin)
- Adds test for the two impacted docs
- Includes new generated SDK API docs from the `make html` bits.
Fixes #450
=> fix(docs): reported issue with example packages

src/steamship/agents/functional/output_parser.py, tests/steamship_tests/agents/test_function_agent_output_parser.py
There was a missed call to `_blocks_from_text` when creating the FinishAction in `FunctionsBasedOutputParser`.   This resulted in returning text instead of Blocks for multimedia.
=> bugfix: Parse output in FunctionsBasedOutputParser

src/steamship/cli/cli.py, src/steamship/cli/deploy.py
Small CLI changes to address version bumping (and typo in serve address).
From:
- `0.0.1` --> `0.0.2-rc.1` (instead of `0.0.1-rc.1`)
-  `https://steamship.com//debug?endpoint=...` to ` https://steamship.com/debug?endpoint=...`
Fixes SHIP-727
=> fix(cli): version bump logic and typo

src/steamship/agents/service/agent_service.py
Without this, the attempt to copy the block content will fail because the URL will be inaccessible.
=> bugfix: Make output blocks public so they can be copied in REPL prompt route

src/steamship/agents/functional/output_parser.py, src/steamship/utils/repl.py, tests/steamship_tests/agents/test_function_agent_output_parser.py
Trailing punctuation blocks are of little to no value (imho). This PR ensures that we don't add those blocks.
From:
```
Here is the image you requested: 
(image/png: B1A98152-A422-4B44-8FD9-D7C954E82D2A)
.
```
To:
```
Here is the image you requested: 
(image/png: B1A98152-A422-4B44-8FD9-D7C954E82D2A)
```
=> fix(agent): don't add blocks that contain only punctuation

tests/assets/plugins/taggers/plugin_parser.py, tests/steamship_tests/agents/test_telegram.py
It looks like in Staging environments, the URL encoding isn't happening (or isn't always happening?). In any case, this attempts to allow flexible results.
=> fix(test): attempt to deflake 'test_telegram' in staging

tests/steamship_tests/data/test_workspace.py
Overlapping CI runs can cause the list of workspaces to expand. This tries to keep the spirit of the test (all workspaces in paged list, no page larger than size requested, next_page_token works), while being more flexible.
=> fix(tests): deflake paging test for workspaces

src/steamship/plugin/outputs/model_checkpoint.py, tests/steamship_tests/plugin/integration/test_e2e_trainable_tagger.py, tests/steamship_tests/plugin/unit/trainable/test_model_checkpoints.py
There is a test flake around DEFAULT checkpoints when multiple test runs happen at the same time. This PR is an attempt to solve that by attempting to rerun the checks until the hashes match.
I don't know if that's the best way to handle this issue, but it was all I could think of at the moment. Someone with a deeper understanding of the intended behavior here could possibly come up with a better solution.
=> fix(tests): add retries to model checkpoint test

src/steamship/agents/tools/base_tools.py, tests/steamship_tests/agents/tools/TestDalleTool.py
We added the public url feature so that chat clients would be able to easily render the output of multimodal blocks, but then we forgot to push the flag all the way up to the Agent Tools.
This PR adds:
- A default of a public block for image/audio/video blocks generated via tools
- Tests that the public URL works
- Tests that it can be set to private via an init arg
cc @maxwfreu who will likely use this in the Vercel integration
=> feat: Use public block URLs for multimodal generations in Tools

.pre-commit-config.yaml
isort's default semantics conflict with black's default semantics. Sometimes this causes an endless loop of disagreement between them during the git precommit hooks.
This configuration line tells isort to behave in a black-compliant way.
=> bugfix: Tell isort to behave in a black-compliant way

src/steamship/data/package/package_instance.py, tests/assets/packages/returns_blocks.py, tests/steamship_tests/app/integration/test_package_instance.py
Hot take:  Getting raw dicts back from `invoke` is a usability concern. Since we are pushing `AgentService` with a builtin `prompt(): -> List[Block]`, we should have an easy way to actually get those blocks directly.
Proposed usage:
```python
answer_blocks = agent.blocks_from_invoke("prompt", prompt="What did I eat for dinner?", context_id="doug-dinner-discussion')
for block in answer_blocks:
print(block.text)
```
=> feat(invoke): add invoke handlers for blocks and task

src/steamship/cli/cli.py
Add a `ship delete` that will allow rapid CLI-based deletion of workspaces and instances.
=> feat(cli): add delete command for workspaces and instances

src/steamship/agents/examples/example_assistant_with_caching.py, src/steamship/agents/functional/output_parser.py, src/steamship/agents/logging.py, src/steamship/agents/schema/action.py, src/steamship/agents/schema/cache.py, src/steamship/agents/schema/context.py, src/steamship/agents/service/agent_service.py, tests/steamship_tests/agents/test_agent_service.py, tests/steamship_tests/agents/test_cache.py, tests/steamship_tests/agents/test_functions_based_agent.py
This is an initial PR for adding caching functionality to Agents. It is aimed at reducing cost and latency for repeated requests.
It attempts to provide two levels of caching:
(1) prompts to the LLMs (prompt-to-Action cache) and (2) action executions (Action-to-outputs cache).
Cache behavior can be dynamically control per call to `prompt`.
NOTE: This PR is NOT introducing semantic caches (text/block uuids must match precisely).
FOLLOW-ONS: Allow Tool-default opt-in/opt-out of caching
=> feat(agents): add caching for LLM calls and Actions

src/steamship/agents/mixins/transports/telegram.py
This PR makes the bot_token optional when using the TelegramMixin. 
* bot_token can be updated with the auth-protected `connect_telegram` route 
* bot_tokens are either passed via the internal kv store OR the config 
* config bot_token takes precedence over the kv-stored bot_token
* Note: kv store is used since config is idempotent.
=> Make Telegram optional

src/steamship/plugin/outputs/raw_data_plugin_output.py, tests/assets/plugins/importers/plugin_file_importer.py, tests/steamship_tests/plugin/integration/test_e2e_file_importer.py
Depends on https://github.com/nludb/nludb/pull/600
Allow FileImporters to return tags in the RawDataPluginOutput.
=> [SHIP-793] Allow tags to be returned in File Importers

src/steamship/agents/examples/telegram_bot.py, src/steamship/agents/mixins/transports/slack.py, src/steamship/agents/mixins/transports/steamship_widget.py, src/steamship/agents/mixins/transports/telegram.py, src/steamship/agents/service/agent_service.py
A handful of user support conversations over the weeks have related to:
1. How do I fetch "my agent" from the service, and
2. How do I modify / build the AgentContext in "situation Y"
This PR:
1. Adds a `get_default_agent` method to AgentService that acts as an official way to get the agent (before it just had a special name, but the code makes it unclear if it was `self.agent` or `self._agent`
2. Adds a `build_default_context` method which implements the standard context that's been copy-pasted every time we write a new endpoint. Now these endpoints can all rely on this `build_default_context` method, and developers can be told that overriding that method will -- for example -- alter the mechanics of their Telegram bot
=> Add a few standardizing methods to AgentService

src/steamship/base/mime_types.py, src/steamship/base/tasks.py, src/steamship/cli/cli.py, src/steamship/cli/local_server/handler.py, src/steamship/data/package/package_instance.py, src/steamship/utils/repl.py
- Fix response unpacking bug in local_server -- It should have been unwrapping the Service response like the Steamship Proxy
- Fix the HttpREPL, which depended upon the improperly unwrapped response (see above)
- Upon `ship run local`, register the local running NGROK URL with the Engine so that it can make async callbacks to it.
=> Support engine-registered development runs in the client

src/steamship/cli/cli.py
CLI says to use `--no_ngrok`, actually need `--no-ngrock`.
=> Fix documentation around --no-ngrok flag

src/steamship/agents/examples/telegram_bot.py
When using Mixins, Mixin config should be a parent class for `AgentService` Config types.
=> fix(agents): update telegram bot example config

src/steamship/agents/mixins/transports/transport.py
parse_inbound takes the `message` from `self._parse_inbound`, which can in some cases be None, causing issues when we try to access `.url` and `.text` off it.
=> Handle None for parse_inbound

docs/nextra/api/steamship.agents.mixins.transports.rst, docs/nextra/index.rst, docs/nextra/make_markdown.sh
* Ignore agent-generate folder
* Ignore react file
=> docs: ignore agent-guidebook and react pages

docs/nextra/agents/index.rst, docs/nextra/data/blocks.rst, docs/nextra/data/files.rst, docs/nextra/data/index.rst, docs/nextra/data/tags.rst, docs/nextra/plugins/developing/generators.rst, docs/nextra/plugins/index.rst, docs/nextra/plugins/using/blockifiers/using.rst, docs/nextra/plugins/using/generators/gpt4.rst, docs/nextra/plugins/using/generators/index.rst, docs/nextra/plugins/using/taggers/using.rst
This is a small opportunistic PR to turn some teletype-strings into documentation links
=> Update RST File, Block, and Tag references to Autodoc links

tests/steamship_tests/utils/deployables.py
`wait_for_init` only checks to see if the initializing phase completes -- not that it succeeded.
This adds an assertion to `deploy_package` and `deploy_plugin` that will more explicitly check that the initialization succeeded to help us weed through some of the random deployment errors that happen in test batteries.
=> Fail tests if plugin/package deployment fails init

src/steamship/agents/examples/telegram_bot.py, src/steamship/agents/mixins/transports/slack.py, src/steamship/agents/mixins/transports/telegram.py, tests/assets/demo_package_spec.json, tests/assets/packages/demo_package.py, tests/assets/packages/transports/test_transports_agent.py, tests/steamship_tests/agents/transports/test_slack.py, tests/steamship_tests/agents/transports/test_telegram.py, tests/steamship_tests/app/integration/test_package_instance.py, tests/steamship_tests/app/unit/test_demo_app_spec.py
This PR:
1. Adds a few additional tests to TelegramTransport
2. Improves TelegramTransport's handling of dynamically set keys (it already had this; this PR makes it a bit more robust)
This will enable a few nice things form a user perspective:
1. Users can re-bind an Agent via the Web UI to a new Telegram Bot
2. Users can defer binding their Agent to a Telegram Bot until after they've created an instance
Follow-on work is a PR to do for Telegram what we just did for Slack in the web UI:
=> Add tests & slight refactor to TelegramTransport key handling

src/steamship/cli/cli.py
The locally running package was attempting to adopt an instance handle from a non-extant Engine response.
In the event that --no-ngrok is specified, this PR assigns the locally running package a fixed constant handle intended to be clearly identified (in debugging logs) as a disconnected locally running copy.
=> bugfix: `ship run local` fails with  `--no-ngrok` flag

src/steamship/base/tasks.py, src/steamship/data/package/package_version.py, src/steamship/data/plugin/plugin_version.py, tests/steamship_tests/utils/deployables.py
This PR introduces a `wait_forever` method on Task, and then uses it for Package & Plugin deployments within tests.
The hope is that some of the occasional deployment timeout failures can be avoided by simply extending the wait time.
(In response to a PR earlier today in which a single failure related to deployment timeouts happened.)
=> fix: CI/CD tests sometimes fail if deployment takes longer than default Task timeout

src/steamship/data/manifest.py, src/steamship/invocable/config.py, tests/steamship_tests/app/unit/test_config_template_extraction.py
Reason: avoid blocking a new SDK version
=> Comment out the optional field support in ConfigTemplate until it's deployed to Engine

src/steamship/base/tasks.py, tests/steamship_tests/base/test_task.py
This PR is part of the work to enable streaming use cases for the Agent SDK. With this change, it will be possible to extract the request ID from a `Task` obj. This request ID can then be used, in concert with a `File`, to stream updates (blocks added).
=> feat(tasks): expose request ID field on Tasks

src/steamship/agents/mixins/transports/telegram.py, tests/steamship_tests/agents/transports/test_telegram.py
I _think_ that in the refactor in https://github.com/steamship-core/python-client/commit/05a8f0e68cc0c343e70915849d2ea3551091ae85 the behavior of the base API for Telegram became to use a `/` in between `bot` and the supplied token. 
Per https://core.telegram.org/bots/api#making-requests, the API base should be:
`https://api.telegram.org/bot<token>/METHOD_NAME`
Note the lack of `/` between `bot` and `<token>`
=> fix(telegram): ensure proper bot API base

src/steamship/data/manifest.py, src/steamship/invocable/config.py, tests/steamship_tests/app/unit/test_config_template_extraction.py
This PR was already code reviewed and merged; it was just merged commented out to wait for the engine to support this field.
=> Enable `optional` config params in client

src/steamship/agents/mixins/transports/telegram.py, tests/assets/packages/transports/mock_telegram_api.py, tests/steamship_tests/agents/transports/test_telegram.py
It looks like back in June, the reporting method which returned information about the bot itself was removed from the transport -- probably accidentally.
This is used to generate a link in the web UI that tells you which bot you've connected your agent to.
=> Add bot handle reporting to Telegram Transport

src/steamship/cli/cli.py
@GitOnUp mentioned this was really surprising to him, and it does feel like bug:
Unless a workspace is specified, `ship run local` will always run the agent in the `default` workspace which means the data and chat histories from multiple runs will be commingled.
This PR:
- Creates a new workspace if one was not specified.
- Reports the workspace in the logging output so you know where you're running
- Alters the semantics if a workspace IS specified to create it if it doesn't already exist.
=> New runs should exist in their own workspace

src/steamship/agents/mixins/transports/slack.py, src/steamship/agents/mixins/transports/steamship_widget.py, src/steamship/agents/mixins/transports/telegram.py, src/steamship/agents/service/agent_service.py, src/steamship/data/block.py
Existing transports were not appending messages sent back to users to the `ChatHistory`. This PR attempts to fix that by introducing a builder for an emit function that will do that directly.
=> fix(history): add emit fn to transports that appends to chat history

src/steamship/agents/examples/example_assistant.py, src/steamship/agents/functional/functions_based.py, src/steamship/agents/functional/output_parser.py, src/steamship/agents/schema/action.py, src/steamship/agents/schema/agent.py, src/steamship/agents/schema/chathistory.py, src/steamship/agents/schema/message_selectors.py, src/steamship/agents/service/agent_service.py, src/steamship/data/tags/tag_constants.py, src/steamship/utils/repl.py, tests/steamship_tests/agents/test_agent_service.py, tests/steamship_tests/agents/test_functions_based_agent.py, tests/steamship_tests/utils/fixtures.py
With the inflight changes for streaming, we unfortunately merged a commit that left message selection in a broken state. The existing testing was not enough to capture the issue. This PR attempts to restore proper message selection functionality.
Follow on PRs will be necessary to clean up and streamline the selection bits added in this PR.
=> fix(agents): generate proper history blocks in agent

docs/nextra/developing/running.rst, docs/nextra/index.rst, docs/nextra/make_markdown.sh
Adds a disclaimer that an ngrok acc is required for running `ship run local`
=> docs: add notice about ngrok acc

.github/workflows/test-main.yml, .github/workflows/test-staging.yml, requirements.dev.txt, src/steamship/agents/functional/functions_based.py, src/steamship/agents/functional/output_parser.py, src/steamship/agents/llms/openai.py, src/steamship/agents/logging.py, src/steamship/agents/schema/action.py, src/steamship/agents/schema/agent.py, src/steamship/agents/schema/chathistory.py, src/steamship/agents/schema/context.py, src/steamship/agents/schema/message_selectors.py, src/steamship/agents/service/agent_service.py, src/steamship/data/block.py, src/steamship/data/file.py, src/steamship/data/tags/tag_constants.py, src/steamship/invocable/invocable_response.py, src/steamship/utils/repl.py, tests/steamship_tests/agents/test_agent_limits.py, tests/steamship_tests/agents/test_agent_service.py, tests/steamship_tests/agents/test_agent_with_final_tool.py, tests/steamship_tests/agents/test_functions_based_agent.py, tests/steamship_tests/utils/fixtures.py
This PR establishes an initial implementation of streaming utilities for `AgentService` endpoints, based on `FunctionsBasedAgent` runs. This will allow clients to invoke an agent run through an async endpoint and stream, via SSE, block creation events related to the agent's execution. These events can include status messages (from Agents and Tools) as well as generated blocks (from LLMs and Tools). 
With this code, new async endpoints can be exposed with code like the following:
```python
@post("async_prompt")
def async_prompt(
self, prompt: Optional[str] = None, context_id: Optional[str] = None, **kwargs
) -> StreamingResponse:
ctx_id, history_file = self._streaming_context_id_and_file(context_id=context_id, **kwargs)
task = self.invoke_later(
"/prompt", arguments={"prompt": prompt, …
```
=> feat(streaming): initial implementation of streaming agentservice execution

src/steamship/cli/cli.py, src/steamship/data/package/package_instance.py, tests/steamship_tests/app/integration/test_package_instance.py
Per discussion on discord: https://discord.com/channels/927675537390968882/927675537390968885/1159144491450630224
Create a command `clean local` which iterates through local development instances of the current package, across workspaces, and asks the user if they wish to delete.  Using the `--all` flag deletes them without prompt.
```
$ ship clean local
Steamship Python CLI version 2.17.31.post1.dev0+g47b0eb17.d20231004
Deleting LOCAL DEVELOPMENT instances of package [my-test-package] across workspaces.
Delete instance [urbane-firefly-rjlch] in workspace [teal-moon-yyeue] created 2023-10-04 20:14:26+00:00 [y/N]: y
Deleted instance [urbane-firefly-rjlch] in workspace [teal-moon-yyeue]
Delete instance [light-shelter-gdgph] in workspace [default] created 2023-10-04 17:42:38+00:00 [y/N]:
``` …
=> CLI command for quickly deleting local development instances

src/steamship/__init__.py, src/steamship/cli/cli.py
During the initialization of the CLI, check the Python version and warn if it's not supported.
I took this approach to attempt to be nice, rather than immediately explode in the SDK itself, though the SDK could certainly leverage the `__init__.py` code here.
-------------
When running on 3.8:
When running on 3.11:
When running on 3.10:
=> Warn against unsupported Python version when running CLI

src/steamship/data/operations/generator.py, src/steamship/data/plugin/plugin_instance.py, tests/steamship_tests/plugin/integration/test_e2e_generator.py
This PR provides the structure for passing Tags into Generation requests.  The Tags that are passed will be applied by the Engine to all Blocks which are created as part of the generate request.
=> Generator Request Tags

src/steamship/plugin/capabilities.py, tests/steamship_tests/plugin/unit/test_capabilities.py
Previous unit tests hid pretty well the fact that NAME wasn't set on capabilities.  Discovered this running unit tests for gpt4.
=> fix: Fix capability name/NAME and add new test
